/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 beard.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/beard-transformed.glb'

export function Beard(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh_0109rip_mat0_0.geometry} material={materials.mat0} position={[0, 10, 0]} rotation={[0, -0.03, -Math.PI]} material-color={props.color}/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(url)
