/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 boyhair.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/boyhair-transformed.glb'


export function Boyhair(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group position={[-1766.62, -1778.61, 13832.69]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.BodyB_mat} position={[1227.24, 1763.19, -8823.15]} scale={5} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(url)
