/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Tiko (https://sketchfab.com/tikoavp)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/braids-hairstyle-476ca30856ff415faff6b23a5f774102
Title: Braids Hairstyle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/braids2-transformed.glb'
export function Braids2(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Braids_Low_Poly_Braid001_Bake1_baked_0.geometry} material={materials['Braid.001_Bake1_baked']} />
          <mesh geometry={nodes.Braids_Low_Poly_Hair_Tips_0.geometry} material={materials.Hair_Tips} />
          <mesh geometry={nodes.Braids_Low_Poly_Black_0.geometry} material={materials.Black} />
        </group>
        <mesh geometry={nodes.Scalp001_Kendrick_Scalp_0.geometry} material={materials.Kendrick_Scalp} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload(url)
