/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: OCBacon (https://sketchfab.com/OCBacon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cornrow-braids-hairstyle-c8052613e7894027a272e5af04ca8da4
Title: Cornrow Braids Hairstyle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/braids-transformed.glb'

export function Braids(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material_002.001']} />
      </group>
    </group>
  )
}

useGLTF.preload(url)
