/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tonytail3.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/tonytail3-transformed.glb'

export function Braids(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material_002.001']} position={[-4, 0, -5]} />
      </group>
    </group>
  )
}

useGLTF.preload(url)
