/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 head_base.gltf --transform
*/

import React, { useRef } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import url from "../../../public/head_base-transformed.glb"

export function Head(props) {
  const { nodes, materials } = useGLTF(url)

  const HiderMat = new THREE.MeshPhongMaterial({
    attach: 'material',
    color: 'hotpink',
    colorWrite: false,
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.head.geometry} material={HiderMat} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(url)
