/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 manhead.gltf --transform
*/

import React, { useRef } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import url from "../../../public/head2-transformed.glb"

export function Head2(props) {
  const { nodes, materials } = useGLTF(url)

  const HiderMat = new THREE.MeshPhongMaterial({
    attach: 'material',
    color: 'hotpink',
    colorWrite: false,
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={HiderMat} position={[0.5, -0.5, 3]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.2, 0.2]} />
      </group>
      <mesh geometry={nodes.Object_2001.geometry} material={HiderMat} rotation={[-Math.PI / 2, 0, 0]} />
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2002.geometry} material={HiderMat} position={[-0.5, -0.5, 3]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.2, 0.2]} />
      </group>
    </group>
  )
}

useGLTF.preload(url)
