/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 low-poly-head.gltf --transform
Author: Tidominer (https://sketchfab.com/tidominer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-head-base-168adcada22243d99a43e759c3016340
Title: Low-Poly Head Base
*/

import React, { useRef } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import url from "../../../public/low-poly-head-transformed.glb"

export function LowpolyHead(props) {
  const { nodes, materials } = useGLTF(url)

  const HiderMat = new THREE.MeshPhongMaterial({
    attach: 'material',
    color: 'hotpink',
    colorWrite: false,
  });
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube__0.geometry} material={HiderMat} rotation={[-Math.PI / 2, 0, 0]} scale={130} />
      </group>
    </group>
  )
}

useGLTF.preload(url)
