/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 malehair.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/malehair-transformed.glb'

export function Malehair(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes['geo_hair-card_3006_hair-cards_0'].geometry} material={materials['hair-cards']} material-color={props.color} position={[-40.48, 43.64, 100.8]} rotation={[-0.44, -0.33, -1.81]} scale={142.05} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(url)
