/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 manhair4.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/manhair4-transformed.glb'

export function ManHair4(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['12'].geometry} material-color={props.color} material={materials['07 - Default.012']} position={[0, -4.14, 0]} scale={5.27} />
    </group>
  )
}

useGLTF.preload(url)
