/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 manhair1.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/manhair1-transformed.glb'

export function ManHair1(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['25'].geometry} material-color={props.color} material={materials['07 - Default']} position={[0, -3, 0]} scale={3.87} />
    </group>
  )
}

useGLTF.preload(url)
