/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 manhair3.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/manhair3-transformed.glb'

export function ManHair3(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['7'].geometry} material-color={props.color} material={materials['07 - Default.008']} position={[0, -4.16, 1.5]} rotation={[-Math.PI / 9, 0.17, 0]} scale={5.62} />
    </group>
  )
}

useGLTF.preload(url)
