/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 medium-hair.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/medium-hair-transformed.glb'

export function MediumHair(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_5.geometry} material={materials['aiStandardSurface1SG.002']} position={[0, 0, -70]} material-color={props.color} scale={0.5} />
      </group>
    </group>
  )
}

useGLTF.preload(url)
