/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Short1.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/Short1-transformed.glb'

export function ShortHair(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Geom.geometry} material={materials.Nancy_Hair} material-color={props.color} />
    </group>
  )
}

useGLTF.preload(url)
