/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 womanhair3.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/womanhair3-transformed.glb'

export function WomanHair3(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material-color={props.color} material={materials['07 - Default.010']} position={[0, -3.62, 0]} scale={4.23} />
    </group>
  )
}

useGLTF.preload(url)
