/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 womanhair1.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/womanhair1-transformed.glb'

export function WomanHair1(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_5.geometry} material={materials['aiStandardSurface1SG.002']} material-color={props.color} position={[0, 0, -70]} scale={0.5} />
      </group>
      <mesh geometry={nodes.Geom.geometry} material-color={props.color} material={materials.Nancy_Hair} />
      <mesh geometry={nodes.Geom001.geometry} material-color={props.color} material={materials.Nancy_Hair} />
    </group>
  )
}

useGLTF.preload(url)
