/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 womanhair2.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from '../../../public/womanhair2-transformed.glb'

export function WomanHair2(props) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['6'].geometry} material-color={props.color} material={materials['07 - Default.006']} position={[0, -3.08, 0]} rotation={[Math.PI, 0, 0]} scale={-4.1} />
    </group>
  )
}

useGLTF.preload(url)
