# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quickstart-ios-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quickstart-ios-swift
  pod 'SwiftSocket'

end
